[package]
name = "dirplayer"
version = "0.1.0"
authors = ["Yann Bonnemay <y.bonnemay@gmail.com>"]

[dependencies]
termion = "*"
serde = { version = "1.0", features = ["derive"] }
serde_json = "*"
serde_derive = "*"
